apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ include "postgres.name" . }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ include "postgres.name" . }}
  type: {{ .Values.service.type }}
