image:
  repository: quay.io/keycloak/keycloak
  tag: "25.0.0"
  pullPolicy: IfNotPresent

keycloak:
  replicas: 1

  databaseVendor: postgres
  databaseHostname: postgres
  databasePort: 5432
  databaseName: keycloak_db
  databaseUser: postgres
  databasePassword: mypassword

  adminUser: admin
  adminPassword: adminpassword

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: keycloak.local
      paths:
        - path: /
          pathType: Prefix
